version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: mongoefarm
    environment:
      MONGO_INITDB_ROOT_USERNAME: newuser
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: testx
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
  redis_c:
    container_name: redis
    image: redis:6.2-alpine
    ports:
      - "127.0.0.1:6379:6379"
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./backend/.env
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #   depends_on:
  #     - backend
